name: watch2earn
description: "Watch2Earn is an app where users earn rewards by watching videos, while managing their favorites and watchlist. With dark/light mode support and a user-friendly design, it provides an enjoyable experience."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1.0.9

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Architecture and DI
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6
  go_router: ^7.1.1

  # API and Storage
  dio: ^5.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.1.1
  flutter_secure_storage: ^8.0.0

  # UI Components
  cached_network_image: ^3.2.3
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  intl: ^0.19.0
  easy_localization: ^3.0.2

  # Ads and Analytics
  google_mobile_ads: ^5.3.1
  firebase_analytics: ^10.4.2

  # Utilities
  equatable: ^2.0.5
  dartz: ^0.10.1
  logger: ^1.3.0
  url_launcher: ^6.1.11
  connectivity_plus: ^4.0.1
  flutter_dotenv: ^5.0.2
  local_auth: ^2.1.6
  package_info_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.4
  hive_generator: ^2.0.0
  mockito: ^5.4.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/
    - .env
    - assets/translations/en.json
    - assets/translations/tr.json
    - assets/translations/de.json
    - assets/translations/fr.json
    - assets/translations/it.json
    - assets/translations/es.json

#  fonts:
#    - family: Poppins
#      fonts:
#        - asset: assets/fonts/Poppins-Regular.ttf
#        - asset: assets/fonts/Poppins-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/Poppins-SemiBold.ttf
#          weight: 600
#        - asset: assets/fonts/Poppins-Bold.ttf
#          weight: 700